  GNU nano 4.8                                                                          docker-compose.yml                                                                                     
version: "3"
services:
    qemu-docker:
        image: w22baka/w22_qemu_docker:v2.0
        tty: true
        command: /root/start.sh
        ports:
            - "5000:5000"
            - "22222:22"
